### ISSUE TITLE
How to install ?!!

### ISSUE THREAD

**Issue by potros** [ThySeth/WastefulDB#1]
Can you please add some text about how to install this package like 

npm i .... --save

**Comment by ThySeth** [comment]
Unfortunately I have yet to publish this to npm. I planned to do so when I had a functioning update feature added but I suppose, if someone such as yourself needs it to be, I'll gladly add it!

**Comment by potros** [comment]
looking forward to install it with npm ( and yarn ) and hope you keep going in this project

**Comment by potros** [comment]
hope this issue is closed when you add it to npm

**Comment by ThySeth** [comment]
npm i wastefuldb

Hopefully things still work. Had to transfer all the files to another folder for publishing.
